version: '3'
services:
 
  application:
    image: osrm-application
    build: ./application
  volumes:
    - ./container-stack-data/osrm:/data:z
  restart: always
  deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  

  nginx:
    image: osrm-nginx-proxy
    build: ./nginx-proxy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./container-stack-data/nginx:/etc/nginx/conf.d:z
      - ./container-stack-data/selfcerts:/certs:roz
    restart: always
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - ./container-stack-data/selfcerts:/certs:z
    environment:
      - SSL_SUBJECT=servhostname.local
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/key.pem
      - SSL_CSR=/certs/key.csr
      - SSL_CERT=/certs/cert.pem
    networks:
      - proxy-tier

# Reference: https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71